version: '3'
services:
    nginx:
        build: ./docker/nginx
        ports:
            # php docker
            - "${PORT_PHP}:80"
            # node docker
            - "${PORT_NODE}:3000"
        env_file:
            - .env
        volumes:
            - ./server/public:/var/www/html/public
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        env_file:
            - .env
        volumes:
            - ./server:/var/www/html
    node:
        build:
            context: .
            dockerfile: ./docker/node/Dockerfile
        restart: always
        env_file:
            - .env
        volumes:
            - .:/var/www/html
        command: sh -c "npm install && npm run dev"